export const actionTypes = {
  SET_USER_INFO: "SET_USER_INFO",
  CREATE_SET: "CREATE_SET",
  UPDATE_SET: "UPDATE_SET",
  EDIT_QUESTION: "EDIT_QUESTION",
  DELETE_SET: "DELETE_SET",
  ADD_QUESTION: "ADD_QUESTION",
};
